version: '3.2'


services:
  key-clock:
    image: quay.io/keycloak/keycloak:15.1.0
    mem_limit: 500m
    ports:
      - "8090:8080"
    environment:
      # KEYCLOAK_USER: admin
      # KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql1
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: keycloak
    # entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
      # DB_PORT: 3307
    # volumes:
      # - "C:\\Users\\Deepa\\learning\\Projects\\TODO\\Allconfiguration\\keyclock:\\opt\\jboss\\keycloak\\"
    networks:
      - todo
    depends_on:
      - mysql1
  mysql1:
    image: mysql:5.7
    # mem_limit: 500m
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    # volumes:
      # - "C:/Users/Deepa/learning/Projects/TODO/Allconfiguration/keyclock:/opt:rw"
    networks:
      - todo
  config-server:
    image: deepakarya0155/spring-config-server:1.0.0
    ports:
      - "8888:8888"
    environment:
      SPRING_SECURITY_USER_NAME: Admin
      SPRING_SECURITY_USER_PASSWORD: Admin
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: /app
    volumes:
      - "C:/Users/Deepa/learning/git_repositoris/CenteralConfigProp:/app:rw"

networks:
  todo: